.build_template:
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

.build_examples_template:
  extends:
    - .build_template
  artifacts:
    when: always
    paths:
      - "**/build*/size.json"
      - "**/build*/build_log.txt"
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_args"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - "**/build*/mmap_build/**/*.bin"
      - "**/build*/**/*.bin"
      - size_info.txt
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
    # By configuring this macro, you can append the compiled configuration file.
    # For example, using "sdkconf.etc=default" specifies the default sdkconfig file.
    EXAMPLE_CONFIG: "="
    EXAMPLE_TARGET: ""
    EXAMPLE_APPEND_ARGS: ""
    EXAMPLE_BOARD: "default"
    BUILD_RECURSIVE: "1"
  script:
    - pip install idf_build_apps esp-bmgr-assist
    - |
      python .gitlab/ci/build_apps.py ${EXAMPLE_DIR} \
              --config ${EXAMPLE_CONFIG} \
              -t ${EXAMPLE_TARGET} \
              -r ${BUILD_RECURSIVE} \
              -vv \
              --board ${EXAMPLE_BOARD} \
              ${EXAMPLE_APPEND_ARGS}

# ESP-IDF v5.1 has reached EOL in Dec 2025.
#
# For Espressif's IDF support policy,
# please refer to
# - https://github.com/espressif/esp-idf/blob/master/SUPPORT_POLICY.md.
# - https://github.com/espressif/esp-idf/blob/master/README.md#esp-idf-release-support-schedule

.build_idf_active_release_version:
  parallel:
    matrix:                               #  EOL date
      - IMAGE: espressif/idf:release-v5.5 # 2028-01-21

build_application_basic_demo:
  extends:
    - .build_examples_template
    - .rules:build:application_basic_demo
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.5
        EXAMPLE_BOARD: esp_SensairHalo
        EXAMPLE_TARGET: esp32c5
      - IMAGE: espressif/idf:release-v5.5
        EXAMPLE_BOARD: esp_SensairShuttle
        EXAMPLE_TARGET: esp32c5
      - IMAGE: espressif/idf:release-v5.5
        EXAMPLE_BOARD: esp_vocat_board_v1_2
        EXAMPLE_TARGET: esp32s3
      - IMAGE: espressif/idf:release-v5.5
        EXAMPLE_BOARD: esp32_S3_DevKitC_1
        EXAMPLE_TARGET: esp32s3
  variables:
    EXAMPLE_DIR: application/basic_demo
